from enum import Enum

class NazionalitaEnum(Enum):
    ITALIA = "Italia"
    COLOMBIA = "Colombia"
    FRANCIA = "Francia"
    SPAGNA = "Spagna"
    REGNO_UNITO = "Regno Unito"
    USA = "USA"

class TipoOperaEnum(Enum):
    ROMANZO = "Romanzo"
    SAGGIO = "Saggio"
    POESIA = "Poesia"
    RACCONTO = "Racconto"
    TEATRO = "Teatro"
    BIOGRAFIA = "Biografia"
    AUTOBIOGRAFIA = "Autobiografia"
    MANUALE = "Manuale"
    ENCICLOPEDIA = "Enciclopedia"
    DIZIONARIO = "Dizionario"
    RIVISTA = "Rivista"
    GIORNALE = "Giornale"
    FUMETTO = "Fumetto"
    GRAPHIC_NOVEL = "Graphic Novel"
    FIABA = "Fiaba"
    FAVOLA = "Favola"
    FANTASCIENZA = "Fantascienza"
    FANTASY = "Fantasy"
    THRILLER = "Thriller"
    GIALLO = "Giallo"
    HORROR = "Horror"
    STORICO = "Storico"
    FILOSOFIA = "Filosofia"
    SCIENZA = "Scienza"
    STORIA = "Storia"
    ARTE = "Arte"
    MUSICA = "Musica"
    RELIGIONE = "Religione"
    DIRITTO = "Diritto"
    ECONOMIA = "Economia"
    INFORMATICA = "Informatica"
    ALTRO = "Altro"